### ISSUE TITLE
Support for Path-Params

### ISSUE THREAD

**Issue by MaZderMind** [httpcache4j/uribuilder#4]
An API to resolve Path-Params (as ie. used in Swagger Code-Documentation) would be useful:

```
URIBuilder.fromString("/rest/api/3/application-properties/{id}")
  .withPathParam("id", "42")
  .build()
```

With an API similar to `.withParameters(…)`

**Comment by hamnis** [comment]
for that you should use a UriTemplate library, this is not in the scope of this project.

like this one: https://github.com/damnhandy/Handy-URI-Templates

**Comment by MaZderMind** [comment]
Thank you @hamnis for the Reference, that perfectly solves my needs. I hope you don't mind me opening a PR wich adds it to the README.
